---
  - name:
    hosts: cisco
    connection: network_cli
    gather_facts: no
    vars_files:
      - vault.yml
    tasks:
      - name: Save running config as fallback
        ios_command:
          commands: copy run flash:/fallback.conf
      - name: Save Section Crypto PKI
        ios_command:
          commands: show run| section crypto pki
          register: certificat
      - name: Register EEM for fallback restore
        ios_command:
          commands:
            - event manager applet fallback
            - event none sync yes
            - action 1 cli command "enable"
            - action 2 cli command "config t"
            - action 3 cli command ""
            - action 4 cli command "exit"
            - action 5 cli command "end"
            - kron policy-list crypto_key
            - cli event manager run crypto_key
            - kron occurence fallback in 5 oneshot
            - policy-list fallback





      - name: Replace running config
        ios_config:
          src: "templates/template.j2"
          replace: block
